/// <reference types="vite/client" />
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

if (!supabaseUrl || supabaseUrl.includes('YOUR_PROJECT')) {
  console.warn('⚠️ Supabase URL not configured. Set VITE_SUPABASE_URL in .env.local');
}

export const supabase = createClient(supabaseUrl || 'https://placeholder.supabase.co', supabaseAnonKey || 'placeholder');

// ─── Types ─────────────────────────────────────────────
export interface Registration {
  id?: string;
  registration_number?: number;
  registration_code?: string;
  full_name: string;
  college_name: string;
  department: string;
  phone: string;
  email: string;
  technical_event: string | null;
  non_technical_event: string | null;
  registration_status?: string;
  created_at?: string;
}

export interface TeamMember {
  id?: string;
  registration_id: string;
  event_type: 'technical' | 'non_technical';
  event_name: string;
  member_number: number;
  member_name: string;
}

// ─── Check duplicate ────────────────────────────────────
export async function checkDuplicateRegistration(phone: string, email: string) {
  const { data, error } = await supabase
    .from('registrations')
    .select('registration_code, full_name')
    .or(`phone.eq.${phone},email.eq.${email.toLowerCase()}`)
    .limit(1);

  if (error) throw error;
  return data && data.length > 0 ? data[0] : null;
}

// ─── Submit registration ────────────────────────────────
export async function submitRegistration(
  reg: Omit<Registration, 'id' | 'registration_number' | 'registration_code' | 'registration_status' | 'created_at'>,
  technicalMembers: string[],
  nonTechnicalMembers: string[]
) {
  // 1) Insert registration → DB generates sequential registration_number via SEQUENCE
  const { data: regData, error: regError } = await supabase
    .from('registrations')
    .insert([{
      ...reg,
      email: reg.email.toLowerCase(),
      registration_status: 'confirmed',
    }])
    .select()
    .single();

  if (regError) throw regError;

  const registrationId = regData.id;
  const registrationCode = regData.registration_code; // generated by DB trigger

  // 2) Insert technical team members
  if (reg.technical_event && technicalMembers.length > 0) {
    const techRows = technicalMembers.map((name, i) => ({
      registration_id: registrationId,
      event_type: 'technical' as const,
      event_name: reg.technical_event as string,
      member_number: i + 1,
      member_name: name,
    }));
    const { error: techErr } = await supabase.from('team_members').insert(techRows);
    if (techErr) throw techErr;
  }

  // 3) Insert non-technical team members
  if (reg.non_technical_event && nonTechnicalMembers.length > 0) {
    const nonTechRows = nonTechnicalMembers.map((name, i) => ({
      registration_id: registrationId,
      event_type: 'non_technical' as const,
      event_name: reg.non_technical_event as string,
      member_number: i + 1,
      member_name: name,
    }));
    const { error: ntErr } = await supabase.from('team_members').insert(nonTechRows);
    if (ntErr) throw ntErr;
  }

  return { ...regData, registration_code: registrationCode } as Registration;
}
